fetch_reclient_cfgs: ignore nacl if the directory doesn't exist
v8 checkout doesn't have native_client.
https://ci.chromium.org/ui/p/v8/builders/ci/V8%20Linux64%20-%20builder%20(reclient)/830/overview

Package infra_internal/rbe/reclient_cfgs/rbe-chromium-trusted/chromium-browser-clang is now tracking "revision/llvmorg-14-init-1380-gee659383-1".
Traceback (most recent call last):
  File "/b/s/w/ir/cache/builder/v8/buildtools/reclient_cfgs/fetch_reclient_cfgs.py", line 86, in <module>
    sys.exit(main())
  File "/b/s/w/ir/cache/builder/v8/buildtools/reclient_cfgs/fetch_reclient_cfgs.py", line 75, in main
    nacl_revision = NaclRevision()
  File "/b/s/w/ir/cache/builder/v8/buildtools/reclient_cfgs/fetch_reclient_cfgs.py", line 25, in NaclRevision
    return subprocess.check_output(
  File "/b/s/w/ir/cipd_bin_packages/cpython3/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/b/s/w/ir/cipd_bin_packages/cpython3/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/b/s/w/ir/cipd_bin_packages/cpython3/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/b/s/w/ir/cipd_bin_packages/cpython3/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/b/s/w/ir/cache/builder/v8/buildtools/reclient_cfgs/../../native_client'

ignore nacl if native_client directory doesn't exist

Change-Id: Ibdbf2a6e83a324913e15ee909be1e5f984b9c3ca
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3115719
Commit-Queue: Fumitoshi Ukai <ukai@google.com>
Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Reviewed-by: Yoshisato Yanagisawa <yyanagisawa@google.com>
Cr-Commit-Position: refs/heads/main@{#915103}
NOKEYCHECK=True
GitOrigin-RevId: d7806fa8413496bcbd43f39a8971dcafeadc663a